CREATE TABLE DIET (
ID INT NOT NULL UNIQUE PRIMARY KEY,
DATE_OF_DIET DATE NOT NULL,
MEAL VARCHAR(100) NOT NULL,
PERSONAL_DATA_ID INT NOT NULL //USER ID
)

CREATE TABLE ACCOUNT_DETAILS (
ID INT NOT NULL UNIQUE PRIMARY KEY,
ACCOUNT_TYPE VARCHAR(50) NOT NULL,
IS_EXPIRED NOT NULL,
IS_BLOCKED NOT NULL
)

CREATE TABLE PERSONAL_DATA (
ID INT NOT NULL UNIQUE PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
SURNAME VARCHAR(30) NOT NULL,
PHONE INT,
EMAIL VARCHAR(30)
)

CREATE TABLE LOGGING_DATA (
LOGIN VARCHAR(20) NOT NULL UNIQUE
PASSWORD VARCHAR(20) NOT NULL
ACCOUNT_DETAILS INT NOT NULL //USER_ID
)

CREATE TABLE TODO (
ID INT NOT NULL UNIQUE PRIMARY KEY
DATE_TODO DATE NOT NULL
NOTE VARCHAR(200) NOT NULL
PERSONAL_DATA INT NOT NULL // USER_ID
)

CREATE TABLE TRAINING (
ID INT NOT NULL UNIQUE PRIMARY KEY,
DATE_TRAINING DATE NOT NULL,
EXERCISE VARCHAR(200) NOT NULL,
PERSONAL_DATA INT NOT NULL //USE_ID
)

INSERT INTO DIET VALUES (1, 10.04.2024, 'salatka', 1)
INSERT INTO ACCOUNT_DETAILS VALUES (1, ADMIN, NOT, NOT, 1)
INSERT INTO PERSONAL_DATA VALUES (1, 'Magda', 'Jot', 501111111, 'magdajot@gmail.com')
INSERT INTO LOGGING_DATA VALUES (1, 'magdaj', 'password123', 1)
INSERT INTO TODO VALUES (1, 10.04.2024, 'zrob obiad', 1)
INSERT INTO TRAINING VALUES (1, 10.04.2024, 'bieganie', 1)