openapi: 3.0.1
info:
  title: API / Diet
  version: 1.0.0-oas3
servers:
  - url: http://localhost/api
tags:
  - name: diets
    description: ''
paths:
  /diets:
    get:
      tags:
        - diets
      summary: Pobiera listę diet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Diet'
  /diets/{diets-id}:
    get:
      tags:
        - diets
      summary: Pobiera dietę
      parameters:
        - name: diet-id
          in: path
          description: Id pobieranej diety
          required: true
          schema:
            type: Long
            format: id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diet'
        '404':
          description: Not found
          content: {}
    put:
      tags:
        - diets
      summary: Dodawanie lub nadpisywanie diety
      parameters:
        - name: diet-id
          in: path
          description: Id pobieranej diety
          required: true
          schema:
            type: Long
            format: id
      requestBody:
        description: Uaktualnione lub wstawione diety
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Diet'
      responses:
        '200':
          description: OK
          content: {}
        '400':
          description: Validation error
          content: {}
    delete:
      tags:
        - diets
      summary: Usuwa dietę
      parameters:
        - name: diet-id
          in: path
          description: Id pobieranej diety
          required: true
          schema:
            type: Long
            format: id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diet'
        '404':
          description: Not found
          content: {}
components:
  schemas:
    Training:
      type: object
      properties:
        td_id:
          type: Long
          format: id
        exercise:
          type: string
        personalData:
          $ref: '#/components/schemas/Diet'
    PersonalData:
      type: object
      properties:
        pd_id:
          type: Long
          format: id