openapi: 3.0.1
info:
  title: API / LoggingData
  version: 1.0.0-oas3
servers:
  - url: http://localhost/api
tags:
  - name: loggingData
    description: ''
paths:
  /loggingData:
    get:
      tags:
        - loggingData
      summary: Pobiera listę użytkowników
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoggingData'
  /loggingData/{loggingData-id}:
    get:
      tags:
        - loggingData
      summary: Pobiera użytkownika
      parameters:
        - name: loggingData-id
          in: path
          description: Id pobieranego użytkownika
          required: true
          schema:
            type: integer
            format: id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggingData'
        '404':
          description: Nie istnieje
          content: {}
    put:
      tags:
        - loggingData
      summary: Nadpisuje użytkownika
      parameters:
        - name: loggingData-id
          in: path
          description: Id pobieranego użytkownika
          required: true
          schema:
            type: integer
            format: id
      requestBody:
        description: Uaktualniany lub wstawiany użytkownik
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoggingData'
        required: true
      responses:
        '200':
          description: OK
          content: {}
        '400':
          description: Błąd walidacji
          content: {}
    delete:
      tags:
        - loggingData
      summary: Usuwa użytkownika
      parameters:
        - name: loggingData-id
          in: path
          description: Id usuwanego użytkownika
          required: true
          schema:
            type: integer
            format: id
      responses:
        '200':
          description: OK
          content: {}
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: id