openapi: 3.0.1
info:
  title: API / ToDo
  version: 1.0.0-oas3
servers:
  - url: http://localhost/api
tags:
  - name: todo
    description: ''
paths:
  /todo:
    get:
      tags:
        - todo
      summary: Pobiera wpisy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                items:
                  $ref: '#/components/schemas/ToDo'
/todo/{todo-uuid}:
  get:
    tags:
      - todo
    summary: Pobiera wpis
    parameters:
      - name: todo-uuid
        in: path
        description: Id pobieranego wpisu
        required: true
        schema:
          type: integer
          format: id
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      '404':
        description: Not found
        content: {}
    put:
      tags:
        - todo
      summary: Dodawanie lub nadpisywanie wpisu
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ToDo'
      parameters:
        - name: todo-uuid
          in: path
          description: Id pobieranego wpisu
          required: true
          schema:
            type: string
            format: id
      requestBody:
        description: Uaktualniony lub wstawiony wpis
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '400':
          description: Validation error
          content: {}
    delete:
      tags:
        - todo
      summary: Usuwa wpis
      parameters:
        - name: todo-id
          in: path
          description: Id pobierania wpisu
          required: true
          schema:
            type: string
            format: id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '404':
          description: Not found
          content: {}
components:
  schema:
    Dashboard:
      type: object
      properties:
        uuid:
          type: string
          format: id
        quantity:
          type: integer
