openapi: 3.0.1
info:
  title: API / ToDo
  version: 1.0.0-oas3
servers:
  - url: http://localhost/api
tags:
  - name: todo
    description: ''
paths:
  /todos:
    get:
      tags:
        - todos
      summary: Pobiera wpisy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                items:
                  $ref: '#/components/schemas/ToDo'
  /todos/{todo-id}:
    get:
      tags:
        - todos
      summary: Pobiera wpis
      parameters:
        - name: todo-id
          in: path
          description: Id pobieranego wpisu
          required: true
          schema:
            type: integer
            format: id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '404':
          description: Not found
          content: {}
    put:
      tags:
        - todos
      summary: Dodawanie lub nadpisywanie wpisu
      parameters:
        - name: todo-id
          in: path
          description: Id pobieranego wpisu
          required: true
          schema:
            type: string
            format: id
      requestBody:
        description: Uaktualniony lub wstawiony wpis
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '400':
          description: Validation error
          content: {}
    delete:
      tags:
        - todo
      summary: Usuwa wpis
      parameters:
        - name: todo-id
          in: path
          description: Id pobierania wpisu
          required: true
          schema:
            type: string
            format: id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
        '404':
          description: Not found
          content: {}
components:
  schemas:
    ToDo:
      type: object
      properties:
        td_id:
          type: integer
          format: id
        note:
          type: string
        personalData:
          $ref: '#/components/schemas/PersonalData'
    PersonalData:
      type: object
      properties:
        pd_id:
          type: integer
          format: id

